name: Update submodules
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  update_submodules:
    name: Update submodules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Update submodules
        run: git submodule update --remote --recursive

      - name: porcelain check
        uses: dorny/paths-filter@v3
        id: data
        with:
          base: HEAD
          filters: |
            changed:
              - '**'

      - name: pnpm generate-data
        if: steps.data.outputs.changed == 'true'
        run: |
          pnpm install --frozen-lockfile --prefer-offline
          pnpm generate-data

      - name: Create Pull Request
        if: steps.data.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: submodule update
          committer: DIM Font Bot <destinyitemmanager@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: 'submodule update: generate-font'
          body: |
            Submodule Update
            generate-font

          branch: submodule-update-v${{ github.event.client_payload.config.env.MANIFEST_VERSION }}
